spring:
  application:
    name: 'redis-distributed-lock'

redis-lock:
  host: 'localhost'
  port: 6379
  connection-timeout: 12
  read-timeout: 13
logging:
  level:
    org:
      springframework:
        data:
         redis:
           connection:
             jedis:
               JedisConnectionFactory: DEBUG
