spring:
  application:
    name: 'redis-distributed-lock'

redis-lock:
  host: 'localhost'
  port: 6379
  connection-timeout: 12
  read-timeout: 13
logging:
  level:
    org:
      springframework: INFO
    iwo:
      wintech: INFO
executor:
  scheduler:
    cron: '*/20 * *  * * *'